irc:
    address: 127.0.0.1:6667
    nick: bot_mcbotface
    user: bots
    channels:
        "#freenode":
            target_chan: general
            ignored_nicks: []

slack:
    channels:
        general: "#freenode"
    secret: $slack_token
    hook_url: integration hook for sending messages

